package main

import (
	exercise3 "my-go-project/week-1/exercise-3"
)

func main() {
	// basics.Packages()
	// basics.Imports()
	// basics.ExportedNames()
	// basics.Functions()
	// basics.FunctionsContinued()
	// basics.MultipleResults()
	// basics.NamedResults()
	// basics.Variables()
	// basics.VariablesWithInitializers()
	// basics.ShortVariableDeclarations()
	// basics.BasicTypes()
	// basics.Zero()
	// basics.TypeConversions()
	// basics.TypeInference()
	// basics.Constants()
	// basics.NumericConstants()
	// flowcontrol.For()
	// flowcontrol.ForContinued()
	// flowcontrol.ForIsGoesWhile()
	// flowcontrol.Forever()
	// flowcontrol.If()
	// flowcontrol.IfWithAShortStatement()
	// flowcontrol.IfAndElse()
	// flowcontrol.ExerviseLoopsAndFunctions()
	// flowcontrol.Switch()
	// flowcontrol.SwitchEvaluaionOrder()
	// flowcontrol.SwitchWithNoCondition()
	// flowcontrol.Defer()
	// flowcontrol.DeferMulti()
	// moretypes.Pointers()
	// moretypes.Structs()
	// moretypes.StructField()
	// moretypes.StructPointers()
	// moretypes.StructLiterals()
	// moretypes.Array()
	// moretypes.Slices()
	// moretypes.SlicesPointer()
	// moretypes.SlicesLiterals()
	// moretypes.SliceBounds()
	// moretypes.SliceLenCap()
	// moretypes.NilSlices()
	// moretypes.MakingSlices()
	// moretypes.SlicesOfSlice()
	// moretypes.Append()
	// moretypes.Range()
	// moretypes.RangeContinued()
	// moretypes.Map()
	// moretypes.MapLiterals()
	// moretypes.MapLiteralsContinued()
	// moretypes.MutatingMaps()
	// moretypes.ExerciseMaps()
	// moretypes.FunctionValues()
	// moretypes.FunctionClosures()
	// moretypes.ExerciseFibonacciClosure()

	exercise3.TempConvertor()
}
